version: '3'
services:
    react-app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '3000:3000'
        volumes:
            - /usr/app/node_modules
            - .:/usr/app
    
    tests:
        build: 
            context: .
            dockerfile: Dockerfile
        command: >
            sh -c "yarn eslint && yarn prettier"
        volumes: 
            - /usr/app/node_modules
            - .:/usr/app

